### ISSUE TITLE
Algorithm negotiation fail

### ISSUE THREAD

**Issue by luckydonald** [agung-m/sshtunnel-ng#3]
![image](https://github.com/agung-m/sshtunnel-ng/assets/2737108/d73c92fe-bcd8-4c88-b1cd-21c03b85e38d)
![image](https://github.com/agung-m/sshtunnel-ng/assets/2737108/cb1e21b9-997f-4f80-b46a-044f8edbf821)

**Comment by luckydonald** [comment]
Not sure how to debug this, are there logs I could attach?

**Comment by agung-m** [comment]
The commit 9d34e99 allows SSH logging per session. It will be applied in the upcoming version 0.6. Please try it.
