### ISSUE TITLE
Feature:  Ability to export/import tunnel configs

### ISSUE THREAD

**Issue by sswift-array** [agung-m/sshtunnel-ng#5]
As an admin, I setup a bunch of tunnel configs for everyone to use, and it would be great if there was the ability to export the configs to some easily importable format.  I know I can move the . file around, but it would be interesting if the import feature allowed for merging in changes instead of just blowing away what the user already has.

This way I can keep the "official" tunnels updated easily for folks, but their custom tunnels don't get impacted.

Thanks!

**Comment by agung-m** [comment]
Thanks. I added this to backlog.

**Comment by agung-m** [comment]
Importing a tunnel configuration from a CSV file has been added (commit 9ec4560).
It will be released along with the export feature that I am working on.

**Comment by agung-m** [comment]
This feature has been released in [v0.7](https://github.com/agung-m/sshtunnel-ng/releases/tag/0.7).
